### ISSUE TITLE
Update profile, patch request

### ISSUE THREAD

**Issue by mitalirs** [pankajkumarbij/easy-job-intern#101]
## Solution
I wish to create a route in the student.js file of the router folder inside the server folder. This path will enable the student to update his/her profile. The student will be able to update include 'name', 'email', 'mobile', 'password' fields. The route permits the student to update the profile only when he/she is authenticated.

## Auth Middleware
The student has to be authenticated for updating the profile. To ensure that, I would like to create a middleware function that will handle the authentication part for the update request.

Sir, could you please assign this issue to me? I am a participant in the GSSoC'21 program.

**Comment by pankajkumarbij** [comment]
@mitalirs are you know React?

You want to work only with the backend without the front-end or both backend and front-end?

**Comment by mitalirs** [comment]
@pankajkumarbij sir, I wish to work on the backend part only as of now, as I have just started exploring react in depth

**Comment by pankajkumarbij** [comment]
@mitalirs Ok you can work on this issue but when make a PR please clear that how to connect it with the front-end and working strategy because when We make the front-end part of this then other contributors should clear about it.

I am in 3rd year So please don't call me sir.

Thanks for opening this issue.

**Comment by mitalirs** [comment]
@pankajkumarbij,  Yes, I will add the details while creating PR. Thank you for assigning this issue.

**Comment by pankajkumarbij** [comment]
@mitalirs are you working on it?

**Comment by mitalirs** [comment]
@pankajkumarbij Yes, I have written the code for update route and auth middleware
But currently, the student object is not keeping track of tokens for the login/signup session of the student. While checking that the student is authenticated before updating, I will need the current JWT token to verify the user. Will it be okay if I add a tokens array on the  'studentSchema'? It will store tokens corresponding to every signup/login session.

**Comment by mitalirs** [comment]
Is this okay? Or I am supposed to create a separate issue for the tokens array property for studentSchema?

**Comment by pankajkumarbij** [comment]
@mitalirs Now please pull all the changes from the original repo because there are many PR merged after you forked there are now both middleware present for companies and students in the server/middleware folder.
When a user is login then it gives a token. Pull changes ad check your requirements are fulfilled or not.

**Comment by mitalirs** [comment]
@pankajkumarbij, yes, I checked it, the changes made will solve my problem.
Thank you

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij, yes, I checked it, the changes made will solve my problem.
> Thank you

ok keep it up

**Comment by mitalirs** [comment]
@pankajkumarbij I have created the Pull Request. Please review it.
