### ISSUE TITLE
Adding authentication middleware

### ISSUE THREAD

**Issue by AbhishekTiwari07** [pankajkumarbij/easy-job-intern#115]
## Is your feature request related to a problem? Please describe.
Current method is not much secure for user authentication.

## Describe the solution you'd like
I'll add reusable authentication middleware that will make APIs more secure and can be used in future too.

## Additional context
It would also help in creating user login session.

**Comment by AbhishekTiwari07** [comment]
pls assign this to me :)

**Comment by pankajkumarbij** [comment]
@AbhishekTiwari07 You can after some time because some backend work related to sign up and login is ongoing.

You can add an authentication middleware after backend work is completed in 2 or 3 days after that I will assign you.

You should make middleware for both student's login and employer login both so I am giving you the Level3 label.

I am putting this issue on hold for now whenever backend work completed I will assign you.

**Comment by AbhishekTiwari07** [comment]
@pankajkumarbij Please let me know when I can start

**Comment by pankajkumarbij** [comment]
@AbhishekTiwari07 till now backend part is not completed.

**Comment by pankajkumarbij** [comment]
@AbhishekTiwari07 Now the backend for signup and login for both companies and students is done.

You can now create middleware files in the server/middleware for both students and employers.
