### ISSUE TITLE
Deleting an internship [Backend + Frontend]

### ISSUE THREAD

**Issue by EkjotKaur** [pankajkumarbij/easy-job-intern#219]
- [x] API for deleting internship
- [x] Drop down menu for edit and delete who be shown only to the creator of the internship post
- [x] Connecting backend to frontend

@pankajkumarbij @asi309 @palashgdev @Vidit-jindal assign me this issue.

**Comment by pankajkumarbij** [comment]
@EkjotKaur when I updating the jobs and fresher's job then existing data is not fetching in that forms. 
please open an issue and solve it.

you can open issues related to deleting jobs and freshers jobs also.

And some backend related to the filter and searching a job or internship is ready you can check the backend and open issues if you are interested to work on that part.

you can make a dashboard for employers and show the details of employers and open jobs, internships and fresher job, etc. because you are also assigned the object id with every job and internship so you can show easily their things.

You can work on the above issues if you are interested.

Thanks.
