### ISSUE TITLE
Creating frontend page for Displaying student profile

### ISSUE THREAD

**Issue by EkjotKaur** [pankajkumarbij/easy-job-intern#482]
Creating frontend page for Displaying student profile

@pankajkumarbij  please assign me this issue.

**Comment by pankajkumarbij** [comment]
@EkjotKaur you can make issues dashboard frontend for the employer also because you are storing all id with all jobs, internship, etc.

show profile of employer.

you have already added delete, update for it.

backend available for delete and update profile you can create many issues if you want and find the work is hard.
you can create issues like add functionality to see internships, jobs created by that employer on the dashboard.

some notification-related backend available you can explore to make frontend.

These above my suggestions, you can create issues if you want to solve them.

**Comment by EkjotKaur** [comment]
Okay, Thank you. I'll create issues related to them.
